"""
AIStudio Visual Models

Defines the visual production plan generated by the Visual Planner.

The Visual Planner operates one scene at a time.

Author : AIStudio
"""

from __future__ import annotations

from typing import Optional
from pydantic import BaseModel, Field


class VisualAsset(BaseModel):
    """
    Production specification for one storyboard scene.

    This is NOT an image prompt.

    It defines the visual direction that the Shot Planner
    and Image Generator will later consume.
    """

    scene_id: str = ""

    visual_type: str = ""

    image_count: int = 1

    environment: str = ""

    subject: str = ""

    lighting: str = ""

    mood: str = ""

    colour_palette: str = ""

    camera_framing: str = ""

    realism_level: str = ""

    reference_requirements: list[str] = Field(
        default_factory=list
    )

    animation_requirements: list[str] = Field(
        default_factory=list
    )

    notes: str = ""


class VisualData(BaseModel):
    """
    Complete visual production plan for the documentary.
    """

    scenes: list[VisualAsset] = Field(
        default_factory=list
    )


class VisualSceneResponse(BaseModel):
    """
    Returned by the LLM when generating visual plans.
    Supports both singular 'scene' and plural 'scenes' payloads.
    """

    scene: Optional[VisualAsset] = None
    scenes: list[VisualAsset] = Field(default_factory=list)