"""
AIStudio Visual Models

Defines the visual production plan generated by the Visual Planner.

The Visual Planner operates one scene at a time and produces the
creative direction that is later expanded into render-ready shots by
the Shot Planner.

Author : AIStudio
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class VisualAsset(BaseModel):
    """
    Creative direction for one documentary scene.
    """

    scene: int = 0

    title: str = ""

    visual_type: str = ""

    image_count: int = 1

    environment: str = ""

    subject: str = ""

    lighting: str = ""

    mood: str = ""

    colour_palette: str = ""

    camera_framing: str = ""

    realism_level: str = ""

    visual_style: str = ""

    continuity_notes: str = ""

    reference_requirements: list[str] = Field(
        default_factory=list,
    )

    animation_requirements: list[str] = Field(
        default_factory=list,
    )

    notes: str = ""


class VisualData(BaseModel):
    """
    Complete visual production plan.
    """

    scenes: list[VisualAsset] = Field(
        default_factory=list,
    )


class VisualSceneResponse(BaseModel):
    """
    Returned by the LLM for one scene.
    """

    scene: VisualAsset